import { useEffect, useMemo, useRef, useState } from "react";
import { Edit3, FilterX, Trash2 } from "lucide-react";
import AdminNav from "../components/AdminNav";
import { AdminNotice, AdminSkeleton, adminButtonClass, adminInputClass } from "../components/AdminUI";
import { createEntrevista, deleteEntrevista, listEmpresas, listEntrevistas, updateEntrevista, updateInterviewStatus } from "../services/ats";
import { listCandidates } from "../services/candidates";
import { listJobs } from "../services/jobs";
import type { Empresa, Entrevista, InterviewStatus } from "../types/ats";
import type { CandidatoComTotal } from "../types/candidates";
import type { Job } from "../types/jobs";
import InterviewStatusActions from "../components/InterviewStatusActions";
import { interviewStatusLabel, normalizeInterviewStatus } from "../lib/interviewStatus";

const MANUAL = "__manual__";
const STATUSES: Array<{ value: InterviewStatus; label: string }> = [{value:"agendada",label:"Agendada"},{value:"confirmada",label:"Confirmada"},{value:"realizada",label:"Realizada"},{value:"reagendada",label:"Reagendada"},{value:"cancelada",label:"Cancelada"},{value:"nao_compareceu",label:"Não compareceu"}];
type FormState={candidateChoice:string;manualName:string;vaga_id:string;empresa_id:string;data:string;horario:string;entrevistador:string;local:string;observacoes:string;status:InterviewStatus};
const EMPTY:FormState={candidateChoice:"",manualName:"",vaga_id:"",empresa_id:"",data:"",horario:"",entrevistador:"",local:"",observacoes:"",status:"agendada"};
const candidateName=(item:Entrevista)=>item.candidato?.nome||item.candidato_nome_manual||"Candidato não informado";

export default function AdminAgendaPage(){
  const[items,setItems]=useState<Entrevista[]>([]),[candidates,setCandidates]=useState<CandidatoComTotal[]>([]),[jobs,setJobs]=useState<Job[]>([]),[companies,setCompanies]=useState<Empresa[]>([]);
  const[form,setForm]=useState<FormState>(EMPTY),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[statusSaving,setStatusSaving]=useState<{id:string;status:InterviewStatus}|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const statusSavingRef=useRef(false);
  const[filters,setFilters]=useState({date:"",status:"",job:"",company:"",query:""});
  async function load(){setError("");try{const[a,b,c,d]=await Promise.all([listEntrevistas(),listCandidates(),listJobs(),listEmpresas()]);setItems(a);setCandidates(b);setJobs(c);setCompanies(d)}catch{setError("Não foi possível carregar todos os dados da agenda. Tente novamente.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function submit(event:React.FormEvent){event.preventDefault();if(saving)return;const manual=form.candidateChoice===MANUAL?form.manualName.trim():"";if((!form.candidateChoice||form.candidateChoice===MANUAL&&!manual)||!form.data||!form.horario){setError("Selecione um candidato ou informe o nome completo, além da data e do horário.");return}setSaving(true);setError("");try{const payload={candidato_id:form.candidateChoice===MANUAL?null:form.candidateChoice,candidato_nome_manual:manual||null,vaga_id:form.vaga_id||null,empresa_id:form.empresa_id||null,data:form.data,horario:form.horario,entrevistador:form.entrevistador||null,local:form.local||null,observacoes:form.observacoes||null,status:form.status};if(editing)await updateEntrevista(editing,payload);else await createEntrevista(payload);setMessage(editing?"Entrevista atualizada com sucesso.":"Entrevista agendada com sucesso.");setForm(EMPTY);setEditing(null);await load()}catch{setError("Não foi possível salvar a entrevista. Verifique os dados e tente novamente.")}finally{setSaving(false)}}
  function edit(item:Entrevista){setEditing(item.id);setForm({candidateChoice:item.candidato_id??MANUAL,manualName:item.candidato_nome_manual??"",vaga_id:String(item.vaga_id??""),empresa_id:item.empresa_id??"",data:item.data,horario:item.horario.slice(0,5),entrevistador:item.entrevistador??"",local:item.local??"",observacoes:item.observacoes??"",status:item.status});window.scrollTo({top:0,behavior:"smooth"})}
  async function changeStatus(id:string,status:InterviewStatus){if(statusSavingRef.current)return;const current=items.find(item=>item.id===id);if(!current||normalizeInterviewStatus(current.status)===normalizeInterviewStatus(status))return;statusSavingRef.current=true;setStatusSaving({id,status});setError("");setMessage("");try{const saved=await updateInterviewStatus(id,status);setItems(rows=>rows.map(item=>item.id===id?{...item,status:saved.status,updated_at:saved.updated_at}:item));setMessage(`Status atualizado para ${interviewStatusLabel(saved.status)}.`)}catch{setError("Não foi possível atualizar o status. O status anterior foi mantido.")}finally{statusSavingRef.current=false;setStatusSaving(null)}}
  async function remove(id:string){if(!window.confirm("Excluir esta entrevista?"))return;try{await deleteEntrevista(id);setItems(current=>current.filter(item=>item.id!==id));setMessage("Entrevista excluída.")}catch{setError("Não foi possível excluir a entrevista.")}}
  const filtered=useMemo(()=>items.filter(item=>(!filters.date||item.data===filters.date)&&(!filters.status||item.status===filters.status)&&(!filters.job||String(item.vaga_id)===filters.job)&&(!filters.company||item.empresa_id===filters.company)&&(!filters.query||candidateName(item).toLocaleLowerCase("pt-BR").includes(filters.query.toLocaleLowerCase("pt-BR")))),[items,filters]);
  const now=new Date(),upcoming=filtered.filter(item=>new Date(`${item.data}T${item.horario}`)>=now),past=filtered.filter(item=>new Date(`${item.data}T${item.horario}`)<now).reverse();
  return <main className="min-h-screen bg-[#F5F7FA]"><AdminNav/><section className="mx-auto max-w-7xl px-5 py-10"><h1 className="text-3xl font-semibold text-[#052656]">Agenda de entrevistas</h1>{message&&<AdminNotice>{message}</AdminNotice>}{error&&<AdminNotice type="error">{error}</AdminNotice>}
    <section className="mt-7 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-2xl font-semibold text-[#052656]">{editing?"Editar entrevista":"Nova entrevista"}</h2><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-3">
      <Select label="Candidato *" value={form.candidateChoice} set={value=>setForm({...form,candidateChoice:value,manualName:value===MANUAL?form.manualName:""})} options={[...candidates.map(item=>[item.id,item.nome]as[string,string]),[MANUAL,"Inserir candidato manualmente"]]}/>
      {form.candidateChoice===MANUAL&&<Field label="Nome do candidato *" value={form.manualName} set={value=>setForm({...form,manualName:value})} placeholder="Digite o nome completo"/>}
      <Select label="Vaga" value={form.vaga_id} set={value=>setForm({...form,vaga_id:value})} options={jobs.map(item=>[String(item.id),item.titulo])}/><Select label="Empresa" value={form.empresa_id} set={value=>setForm({...form,empresa_id:value})} options={companies.map(item=>[item.id,item.nome])}/>
      <Field label="Data *" type="date" value={form.data} set={value=>setForm({...form,data:value})}/><Field label="Horário *" type="time" value={form.horario} set={value=>setForm({...form,horario:value})}/><Select label="Status" value={form.status} set={value=>setForm({...form,status:value as InterviewStatus})} options={STATUSES.map(item=>[item.value,item.label])}/><Field label="Entrevistador" value={form.entrevistador} set={value=>setForm({...form,entrevistador:value})}/><Field label="Local" value={form.local} set={value=>setForm({...form,local:value})}/>
      <label className="md:col-span-3"><span className="mb-2 block font-semibold">Observações</span><textarea value={form.observacoes} onChange={event=>setForm({...form,observacoes:event.target.value})} className={adminInputClass}/></label><div className="flex flex-wrap gap-3"><button disabled={saving} className={adminButtonClass("primary")}>{saving?"Salvando...":editing?"Salvar alterações":"Agendar entrevista"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(EMPTY)}} className={adminButtonClass("secondary")}>Cancelar edição</button>}</div>
    </form></section>
    <section className="mt-7 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold text-[#052656]">Filtros</h2><div className="mt-4 grid gap-4 md:grid-cols-5"><Field label="Data" type="date" value={filters.date} set={value=>setFilters({...filters,date:value})}/><Select label="Status" value={filters.status} set={value=>setFilters({...filters,status:value})} options={STATUSES.map(item=>[item.value,item.label])}/><Select label="Vaga" value={filters.job} set={value=>setFilters({...filters,job:value})} options={jobs.map(item=>[String(item.id),item.titulo])}/><Select label="Empresa" value={filters.company} set={value=>setFilters({...filters,company:value})} options={companies.map(item=>[item.id,item.nome])}/><Field label="Buscar candidato" value={filters.query} set={value=>setFilters({...filters,query:value})}/></div><button onClick={()=>setFilters({date:"",status:"",job:"",company:"",query:""})} className={`${adminButtonClass("secondary")} mt-4`}><FilterX size={16}/>Limpar filtros</button></section>
    {loading?<div className="mt-7"><AdminSkeleton/></div>:<><InterviewList title="Próximas entrevistas" items={upcoming} edit={edit} status={changeStatus} remove={remove} statusSaving={statusSaving}/><InterviewList title="Entrevistas anteriores" items={past} edit={edit} status={changeStatus} remove={remove} statusSaving={statusSaving}/></>}
  </section></main>;
}

function InterviewList({title,items,edit,status,remove,statusSaving}:{title:string;items:Entrevista[];edit:(item:Entrevista)=>void;status:(id:string,status:InterviewStatus)=>Promise<void>;remove:(id:string)=>Promise<void>;statusSaving:{id:string;status:InterviewStatus}|null}){return <section className="mt-7"><h2 className="text-2xl font-semibold text-[#052656]">{title}</h2>{!items.length?<p className="mt-4 bg-white p-6 text-gray-500">Nenhuma entrevista encontrada.</p>:<div className="mt-4 grid gap-4 lg:grid-cols-2">{items.map(item=><article key={item.id} className="border-l-4 border-[#D4A62A] bg-white p-5 shadow-sm"><time className="font-semibold text-[#052656]">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.data}T12:00`))} às {item.horario.slice(0,5)}</time><h3 className="mt-1 text-xl font-semibold">{candidateName(item)}</h3><p className="text-gray-600">{item.vaga?.titulo||"Sem vaga"} · {item.empresa?.nome||"Sem empresa"}</p><p>{item.entrevistador||"Entrevistador não informado"} · {item.local||"Local não informado"}</p><div className="mt-4"><InterviewStatusActions currentStatus={item.status} processingStatus={statusSaving?.id===item.id?statusSaving.status:null} disabled={Boolean(statusSaving&&statusSaving.id!==item.id)} onChange={next=>status(item.id,next)}/></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-gray-200 pt-4"><button type="button" onClick={()=>edit(item)} className={adminButtonClass("secondary")}><Edit3 size={15}/>Editar</button><button type="button" onClick={()=>void remove(item.id)} className={adminButtonClass("danger")}><Trash2 size={15}/>Excluir</button></div></article>)}</div>}</section>}
function Select({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:Array<[string,string]>}){return <label><span className="mb-2 block font-semibold">{label}</span><select value={value} onChange={event=>set(event.target.value)} className={adminInputClass}><option value="">Selecione</option>{options.map(([option,label])=><option key={option} value={option}>{label}</option>)}</select></label>}
function Field({label,value,set,type="text",placeholder}:{label:string;value:string;set:(value:string)=>void;type?:string;placeholder?:string}){return <label><span className="mb-2 block font-semibold">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={event=>set(event.target.value)} className={adminInputClass}/></label>}
