import type { EtapaProcesso } from "./candidates";
import type { JobStatus } from "./jobs";
export type CompanyUser={id:string;empresa_id:string;user_id:string;nome:string;email:string;ativo:boolean;created_at:string;updated_at:string};
export type ClientCompany={id:string;nome:string;logo_url:string|null;status:"ativo"|"inativo"};
export type PortalJob={id:string|number;empresa_id:string|null;titulo:string;descricao:string|null;atividades:string|null;requisitos:string|null;beneficios:string|null;cidade:string;estado:string;modalidade:string|null;tipo_contrato:string|null;quantidade_vagas:number;status:JobStatus;created_at:string};
export type PortalApplication={id:string;candidato_id:string;vaga_id:string|number|null;etapa:EtapaProcesso;portal_liberado:boolean;portal_liberado_em:string|null;resumo_cliente:string|null;pontos_positivos_cliente:string|null;pontos_atencao_cliente:string|null;curriculo_liberado:boolean;data_admissao:string|null;created_at:string;updated_at:string};
export type PortalCandidate={id:string;nome:string;cidade:string|null;estado:string|null;curriculo_url:string|null;created_at:string;updated_at:string};
export type PortalInterview={id:string;candidatura_id:string|null;tipo_entrevista:"cliente";modalidade:"presencial"|"online"|null;data:string;horario:string;local:string|null;status:string;observacoes_cliente:string|null;updated_at:string};
export type ClientDecision="quero_entrevistar"|"aprovado_empresa"|"nao_aprovado"|"solicitar_informacoes";
export type ClientFeedback={id:string;candidatura_id:string;decisao:ClientDecision;comentario:string|null;created_at:string;updated_at:string};
export type FeedbackServiceStatus="pendente"|"em_andamento"|"concluido";
export type AdminClientFeedback=ClientFeedback&{empresa_id:string;user_id:string;lido_em:string|null;lido_por:string|null;status_atendimento:FeedbackServiceStatus;atendimento_iniciado_em:string|null;concluido_em:string|null;tratado_por:string|null;empresa:{id:string;nome:string}|null;candidatura:{id:string;candidato_id:string;vaga_id:string|number|null;candidato:{id:string;nome:string}|null;vaga:{id:string|number;titulo:string}|null}|null};
