import { supabase } from "../lib/supabase";
import type { AdminClientFeedback, FeedbackServiceStatus } from "../types/clientPortal";
import type { AdminFeedbackAction } from "../components/AdminFeedbackActions";

const SELECT="id,candidatura_id,empresa_id,user_id,decisao,comentario,lido_em,lido_por,status_atendimento,atendimento_iniciado_em,concluido_em,tratado_por,created_at,updated_at,empresa:empresas(id,nome),candidatura:candidaturas(id,candidato_id,vaga_id,candidato:candidatos(id,nome),vaga:vagas(id,titulo))";
export async function listAdminFeedbacks(){const{data,error}=await supabase.from("feedbacks_cliente").select(SELECT).order("updated_at",{ascending:false});if(error)throw error;return(data??[])as unknown as AdminClientFeedback[]}
export async function updateFeedbackService(item:AdminClientFeedback,status:AdminFeedbackAction){if(status==="lida"&&item.lido_em)return;if(status==="em_andamento"&&item.status_atendimento!=="pendente")return;if(status==="concluido"&&item.status_atendimento==="concluido")return;const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão administrativa expirada.");const now=new Date().toISOString();const payload=status==="lida"?{lido_em:now,lido_por:user.id}:status==="em_andamento"?{status_atendimento:status,atendimento_iniciado_em:now,tratado_por:user.id,lido_em:now,lido_por:user.id,updated_at:now}:{status_atendimento:"concluido" as FeedbackServiceStatus,concluido_em:now,tratado_por:user.id,lido_em:now,lido_por:user.id,updated_at:now};let query=supabase.from("feedbacks_cliente").update(payload).eq("id",item.id);if(status==="concluido")query=query.neq("status_atendimento","concluido");if(status==="em_andamento")query=query.eq("status_atendimento","pendente");const{error}=await query;if(error)throw error}

export function applyFeedbackAction(item:AdminClientFeedback,status:AdminFeedbackAction):AdminClientFeedback{const now=new Date().toISOString();if(status==="lida")return{...item,lido_em:item.lido_em??now};if(status==="em_andamento")return{...item,status_atendimento:"em_andamento",atendimento_iniciado_em:now,lido_em:item.lido_em??now,updated_at:now};return{...item,status_atendimento:"concluido",concluido_em:now,lido_em:item.lido_em??now,updated_at:now}}
export function feedbackDecisionLabel(value:AdminClientFeedback["decisao"]){return({quero_entrevistar:"Quero entrevistar",aprovado_empresa:"Aprovado pela empresa",nao_aprovado:"Não aprovado",solicitar_informacoes:"Solicitar mais informações"})[value]}
export function feedbackActionLabel(value:AdminClientFeedback["decisao"]){return({quero_entrevistar:"Entrar em contato com o candidato",aprovado_empresa:"Revisar aprovação",nao_aprovado:"Revisar feedback",solicitar_informacoes:"Responder solicitação"})[value]}
