import { supabase } from "../lib/supabase";
import { normalizeFeedbackStatus } from "../lib/feedbackStatus";
import type { AdminClientFeedback, FeedbackServiceStatus } from "../types/clientPortal";

export type AdminFeedbackAction = "lida" | "em_andamento" | "concluido";

const SELECT="id,candidatura_id,empresa_id,user_id,decisao,comentario,lido_em,lido_por,status_atendimento,atendimento_iniciado_em,concluido_em,tratado_por,created_at,updated_at,empresa:empresas(id,nome),candidatura:candidaturas(id,candidato_id,vaga_id,candidato:candidatos(id,nome),vaga:vagas(id,titulo))";
export async function listAdminFeedbacks(){const{data,error}=await supabase.from("feedbacks_cliente").select(SELECT).order("updated_at",{ascending:false});if(error)throw error;return(data??[])as unknown as AdminClientFeedback[]}
export async function updateFeedbackService(item:AdminClientFeedback,status:AdminFeedbackAction):Promise<AdminClientFeedback|null>{const normalized=normalizeFeedbackStatus(item.status_atendimento);if(status==="lida"&&item.lido_em)return item;if(status==="em_andamento"&&normalized!=="pendente")return item;if(status==="concluido"&&normalized==="concluido")return item;const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão administrativa expirada.");const now=new Date().toISOString();const payload=status==="lida"?{lido_em:now,lido_por:user.id}:status==="em_andamento"?{status_atendimento:status,atendimento_iniciado_em:now,tratado_por:user.id,lido_em:now,lido_por:user.id,updated_at:now}:{status_atendimento:"concluido" as FeedbackServiceStatus,concluido_em:now,tratado_por:user.id,lido_em:now,lido_por:user.id,updated_at:now};let query=supabase.from("feedbacks_cliente").update(payload).eq("id",item.id);if(status==="concluido")query=query.neq("status_atendimento","concluido");if(status==="em_andamento")query=query.eq("status_atendimento","pendente");const{data,error}=await query.select(SELECT).maybeSingle();if(error)throw error;return data as unknown as AdminClientFeedback|null}

export function feedbackDecisionLabel(value:AdminClientFeedback["decisao"]){return({quero_entrevistar:"Quero entrevistar",aprovado_empresa:"Aprovado pela empresa",nao_aprovado:"Não aprovado",solicitar_informacoes:"Solicitar mais informações"})[value]}
export function feedbackActionLabel(value:AdminClientFeedback["decisao"]){return({quero_entrevistar:"Entrar em contato com o candidato",aprovado_empresa:"Revisar aprovação",nao_aprovado:"Revisar feedback",solicitar_informacoes:"Responder solicitação"})[value]}
