import { supabase } from "../lib/supabase";
import type { Empresa, EmpresaForm, Entrevista, HistoricoCandidato, ObservacaoInterna } from "../types/ats";
export async function listEmpresas(){ const {data,error}=await supabase.from("empresas").select("*").order("nome"); if(error)throw error; return (data??[]) as Empresa[]; }
export async function getEmpresa(id:string){ const {data,error}=await supabase.from("empresas").select("*").eq("id",id).single(); if(error)throw error; return data as Empresa; }
export async function saveEmpresa(form:EmpresaForm,id?:string){ const payload={...form,updated_at:new Date().toISOString()}; const query=id?supabase.from("empresas").update(payload).eq("id",id).select("*").single():supabase.from("empresas").insert(payload).select("*").single(); const {data,error}=await query; if(error)throw error; return data as Empresa; }
export async function listEntrevistas(){ const {data,error}=await supabase.from("entrevistas").select("*,candidato:candidatos(id,nome),vaga:vagas(id,titulo),empresa:empresas(id,nome)").order("data").order("horario"); if(error)throw error; return (data??[]) as unknown as Entrevista[]; }
export async function createEntrevista(form:Omit<Entrevista,"id"|"created_at"|"updated_at"|"candidato"|"vaga"|"empresa">){ const {error}=await supabase.from("entrevistas").insert(form); if(error)throw error; }
export async function updateEntrevista(id:string,form:Omit<Entrevista,"id"|"created_at"|"updated_at"|"candidato"|"vaga"|"empresa">){const{error}=await supabase.from("entrevistas").update({...form,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;}
export async function updateInterviewStatus(id:string,status:Entrevista["status"]){const{error}=await supabase.from("entrevistas").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;}
export async function deleteEntrevista(id:string){const{error}=await supabase.from("entrevistas").delete().eq("id",id);if(error)throw error;}
export async function listHistorico(candidateId:string){ const {data,error}=await supabase.from("historico_candidatos").select("*").eq("candidato_id",candidateId).order("created_at",{ascending:false}); if(error)throw error; return (data??[]) as HistoricoCandidato[]; }
export async function addHistorico(candidateId:string,evento:string,observacao?:string,candidaturaId?:string){ const {data:{user}}=await supabase.auth.getUser(); const {error}=await supabase.from("historico_candidatos").insert({candidato_id:candidateId,candidatura_id:candidaturaId??null,evento,observacao:observacao?.trim()||null,responsavel:user?.id??null}); if(error)throw error; }
export async function listNotas(candidateId:string){ const {data,error}=await supabase.from("observacoes_internas").select("*").eq("candidato_id",candidateId).order("created_at",{ascending:false}); if(error)throw error; return (data??[]) as ObservacaoInterna[]; }
export async function addNota(candidateId:string,texto:string){ const {data:{user}}=await supabase.auth.getUser(); const {error}=await supabase.from("observacoes_internas").insert({candidato_id:candidateId,usuario_id:user?.id??null,texto:texto.trim()}); if(error)throw error; }
