import { supabase } from "../lib/supabase";
import type { ClientCompany,ClientDecision,ClientFeedback,CompanyUser,PortalApplication,PortalCandidate,PortalInterview,PortalJob } from "../types/clientPortal";
const LINK_COLUMNS="id,empresa_id,user_id,nome,email,ativo,created_at,updated_at";
const JOB_COLUMNS="id,empresa_id,titulo,descricao,atividades,requisitos,beneficios,cidade,estado,modalidade,tipo_contrato,quantidade_vagas,status,created_at";
const APPLICATION_COLUMNS="id,candidato_id,vaga_id,etapa,portal_liberado,portal_liberado_em,resumo_cliente,pontos_positivos_cliente,pontos_atencao_cliente,curriculo_liberado,created_at";
export async function getClientContext(){const{data:links,error}=await supabase.from("empresa_usuarios").select(LINK_COLUMNS).eq("ativo",true).order("created_at");if(error)throw error;const typed=(links??[])as CompanyUser[];if(!typed.length)return{links:[],companies:[]};const{data:companies,error:companyError}=await supabase.from("empresas").select("id,nome,logo_url,status").in("id",typed.map(x=>x.empresa_id));if(companyError)throw companyError;return{links:typed,companies:(companies??[])as ClientCompany[]}}
export async function listPortalJobs(companyId:string){const{data,error}=await supabase.from("vagas").select(JOB_COLUMNS).eq("empresa_id",companyId).neq("status","excluida").order("created_at",{ascending:false});if(error)throw error;return(data??[])as PortalJob[]}
export async function listPortalApplications(jobIds:Array<string|number>){if(!jobIds.length)return[];const{data,error}=await supabase.from("candidaturas").select(APPLICATION_COLUMNS).in("vaga_id",jobIds).eq("portal_liberado",true).order("portal_liberado_em",{ascending:false});if(error)throw error;return(data??[])as PortalApplication[]}
export async function listPortalCandidates(ids:string[]){if(!ids.length)return[];const{data,error}=await supabase.from("candidatos").select("id,nome,cidade,area,experiencia,curriculo_url,created_at").in("id",ids);if(error)throw error;return(data??[])as PortalCandidate[]}
export async function listPortalInterviews(jobIds:Array<string|number>){if(!jobIds.length)return[];const{data,error}=await supabase.from("entrevistas").select("id,candidato_id,vaga_id,data,horario,local,status").in("vaga_id",jobIds).gte("data",new Date().toISOString().slice(0,10)).order("data").order("horario");if(error)throw error;return(data??[])as PortalInterview[]}
export async function listClientFeedbacks(companyId:string){const{data,error}=await supabase.from("feedbacks_cliente").select("id,candidatura_id,empresa_id,user_id,decisao,comentario,created_at,updated_at").eq("empresa_id",companyId);if(error)throw error;return(data??[])as ClientFeedback[]}
export async function saveClientFeedback(applicationId:string,companyId:string,decision:ClientDecision,comment:string){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão expirada.");const payload={candidatura_id:applicationId,empresa_id:companyId,user_id:user.id,decisao:decision,comentario:comment.trim()||null,updated_at:new Date().toISOString()};const{data,error}=await supabase.from("feedbacks_cliente").upsert(payload,{onConflict:"candidatura_id,empresa_id"}).select("id,candidatura_id,empresa_id,user_id,decisao,comentario,created_at,updated_at").single();if(error)throw error;return data as ClientFeedback}
export async function signedPortalResume(path:string){const{data,error}=await supabase.storage.from("curriculos").createSignedUrl(path,120);if(error)throw error;return data.signedUrl}
