import { clientPortalSupabase as supabase } from "../lib/clientPortalSupabase";
import type { ClientCompany,ClientDecision,ClientFeedback,CompanyUser,PortalApplication,PortalCandidate,PortalInterview,PortalJob } from "../types/clientPortal";
import type { PortalContract } from "../types/companyContracts";
const LINK_COLUMNS="id,empresa_id,user_id,nome,email,ativo,created_at,updated_at";
const JOB_COLUMNS="id,empresa_id,titulo,descricao,atividades,requisitos,beneficios,cidade,estado,modalidade,tipo_contrato,quantidade_vagas,status,created_at";
export async function getClientContext(){const{data:links,error}=await supabase.from("empresa_usuarios").select(LINK_COLUMNS).eq("ativo",true).order("created_at");if(error)throw error;const typed=(links??[])as CompanyUser[];if(!typed.length)return{links:[],companies:[]};const{data:companies,error:companyError}=await supabase.from("empresas").select("id,nome,logo_url,status").in("id",typed.map(x=>x.empresa_id));if(companyError)throw companyError;return{links:typed,companies:(companies??[])as ClientCompany[]}}
export async function listPortalJobs(companyId:string){const{data,error}=await supabase.from("vagas").select(JOB_COLUMNS).eq("empresa_id",companyId).neq("status","excluida").order("created_at",{ascending:false});if(error)throw error;return(data??[])as PortalJob[]}
export async function listPortalApplications(jobIds:Array<string|number>){if(!jobIds.length)return[];const{data,error}=await supabase.rpc("portal_list_client_applications",{p_job_ids:jobIds.map(Number)});if(error)throw error;return(data??[])as PortalApplication[]}
export async function listPortalCandidates(ids:string[]){if(!ids.length)return[];const{data,error}=await supabase.rpc("portal_list_client_candidates",{p_candidate_ids:ids});if(error)throw error;return(data??[])as PortalCandidate[]}
export async function listPortalInterviews(jobIds:Array<string|number>){if(!jobIds.length)return[];const{data,error}=await supabase.rpc("portal_list_client_interviews",{p_job_ids:jobIds.map(Number)});if(error)throw error;return(data??[])as PortalInterview[]}
export async function listClientFeedbacks(applicationIds:string[]){if(!applicationIds.length)return[];const{data,error}=await supabase.rpc("portal_list_client_feedbacks",{p_candidatura_ids:applicationIds});if(error)throw error;return(data??[])as ClientFeedback[]}
export async function saveClientFeedback(applicationId:string,_companyId:string,decision:ClientDecision,comment:string){const{data,error}=await supabase.rpc("portal_submit_client_feedback",{p_candidatura_id:applicationId,p_decisao:decision,p_comentario:comment.trim()||null});if(error)throw error;return data as string}
export async function signedPortalResume(path:string){const{data,error}=await supabase.storage.from("curriculos").createSignedUrl(path,120);if(error)throw error;return data.signedUrl}
export async function listPortalContracts(companyId:string){const{data,error}=await supabase.rpc("portal_list_released_contracts",{p_empresa_id:companyId});if(error)throw error;return(data??[])as PortalContract[]}
export async function signedPortalContract(contract:PortalContract,download:boolean){const{error:auditError}=await supabase.rpc("portal_record_contract_access",{p_contrato_id:contract.id,p_acao:download?"download":"visualizacao"});if(auditError)throw auditError;const{data,error}=await supabase.storage.from("contratos-clientes").createSignedUrl(contract.caminho_arquivo,120,download?{download:contract.nome_arquivo??true}:undefined);if(error)throw error;return data.signedUrl}
