import{ supabase }from"../lib/supabase";import type{CompanyContract,CompanyContractForm,ContractPortalAudit,ContractStatus}from"../types/companyContracts";
const BUCKET="contratos-clientes",MAX=10*1024*1024,ALLOWED=["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],EXTENSIONS=["pdf","doc","docx"];
export function validateContract(file:File){const extension=file.name.split(".").pop()?.toLowerCase()??"";if(file.size>MAX)throw new Error("O contrato deve ter no máximo 10 MB.");if(!EXTENSIONS.includes(extension)||!ALLOWED.includes(file.type))throw new Error("Envie um contrato em PDF, DOC ou DOCX.");}
export async function listCompanyContracts(empresaId?:string){let query=supabase.from("contratos_clientes").select("*").order("created_at",{ascending:false});if(empresaId)query=query.eq("empresa_id",empresaId);const{data,error}=await query;if(error)throw error;return(data??[])as CompanyContract[];}
export async function saveCompanyContract(empresaId:string,form:CompanyContractForm,id?:string){const payload={empresa_id:empresaId,...form,data_vencimento:form.data_vencimento||null,forma_cobranca:form.forma_cobranca.trim()||null,observacoes:form.observacoes.trim()||null,updated_at:new Date().toISOString()};const query=id?supabase.from("contratos_clientes").update(payload).eq("id",id).select("*").single():supabase.from("contratos_clientes").insert(payload).select("*").single();const{data,error}=await query;if(error)throw error;return data as CompanyContract;}
export async function uploadCompanyContract(contract:CompanyContract,file:File){validateContract(file);const safe=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${contract.empresa_id}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from(BUCKET).upload(path,file,{contentType:file.type});if(uploadError)throw uploadError;const old=contract.caminho_arquivo;const{data,error}=await supabase.from("contratos_clientes").update({nome_arquivo:file.name,caminho_arquivo:path,contrato_data_upload:new Date().toISOString(),status_contrato:"vigente",portal_liberado:false,portal_liberado_em:null,portal_liberado_por:null,updated_at:new Date().toISOString()}).eq("id",contract.id).select("*").single();if(error){await supabase.storage.from(BUCKET).remove([path]);throw error;}if(old)await supabase.storage.from(BUCKET).remove([old]);return data as CompanyContract;}
export async function signedContractUrl(path:string,download=false){const{data,error}=await supabase.storage.from(BUCKET).createSignedUrl(path,300,{download});if(error)throw error;return data.signedUrl;}
export async function deleteContractFile(contract:CompanyContract){if(contract.caminho_arquivo){const{error}=await supabase.storage.from(BUCKET).remove([contract.caminho_arquivo]);if(error)throw error;}const{error}=await supabase.from("contratos_clientes").update({nome_arquivo:null,caminho_arquivo:null,contrato_data_upload:null,status_contrato:"pendente",portal_liberado:false,portal_liberado_em:null,portal_liberado_por:null,updated_at:new Date().toISOString()}).eq("id",contract.id);if(error)throw error;}
export async function saveContractPortalRelease(contractId:string,release:boolean,status:ContractStatus){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sessão administrativa expirada.");const now=new Date().toISOString();const{data,error}=await supabase.from("contratos_clientes").update({status_contrato:status,portal_liberado:release,portal_liberado_em:release?now:null,portal_liberado_por:release?user.id:null,updated_at:now}).eq("id",contractId).select("*").single();if(error)throw error;return data as CompanyContract;}
export async function listContractPortalAudit(contractId:string){const{data,error}=await supabase.from("portal_contratos_auditoria").select("id,contrato_id,empresa_id,usuario_id,acao,created_at").eq("contrato_id",contractId).order("created_at",{ascending:false}).limit(20);if(error)throw error;return(data??[])as ContractPortalAudit[];}
